# netlify.toml

# This tells Netlify where your serverless functions are located.
[build]
  functions = "netlify/functions"

# This is the crucial fix: It tells Netlify to use the official plugin 
# to automatically find and install the dependencies for your functions.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# This section configures the functions themselves.
[functions]
  node_bundler = "esbuild"

